name: Deploy to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ðŸ“ Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: ðŸš€ SSH to EC2 and deploy
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "ðŸ“ ÐšÐ¾Ð¿Ñ–ÑŽÑŽ Ð¿Ñ€Ð¾ÐµÐºÑ‚ Ñƒ Ñ‚Ð¸Ð¼Ñ‡Ð°ÑÐ¾Ð²Ñƒ Ð¿Ð°Ð¿ÐºÑƒ..."
            rm -rf my-cloud-ui-temp
            cp -r my-cloud-ui my-cloud-ui-temp
            cd my-cloud-ui-temp

            echo "ðŸ“¦ Ð’ÑÑ‚Ð°Ð½Ð¾Ð²Ð»ÐµÐ½Ð½Ñ Ð·Ð°Ð»ÐµÐ¶Ð½Ð¾ÑÑ‚ÐµÐ¹..."
            npm install

            echo "ðŸ“¦ Starting build..."
            NODE_ENV=production npm run build

            echo "ðŸ§¹ Ð’ÑÐµ Ð¾Ðº, Ð¾Ð½Ð¾Ð²Ð»ÑŽÑŽ Ð¿Ñ€Ð¾Ð´Ð°ÐºÑˆÐ½ Ð²ÐµÑ€ÑÑ–ÑŽ..."
            cd ..
            pm2 delete my-cloud-ui || true
            rm -rf my-cloud-ui
            mv my-cloud-ui-temp my-cloud-ui

            echo "ðŸš€ Ð—Ð°Ð¿ÑƒÑÐºÐ°ÑŽ Ð½Ð¾Ð²Ñƒ Ð²ÐµÑ€ÑÑ–ÑŽ..."
            cd my-cloud-ui
            pm2 start "npm run start" --name my-cloud-ui
            pm2 save
          EOF

      - name: ðŸŸ¢ Telegram success message
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT_ID }} \
            -d text="âœ… Deploy to EC2 succeeded!"

      - name: ðŸ”´ Telegram failure message
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT_ID }} \
            -d text="âŒ Deploy to EC2 failed!"
